// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDgnR-BFNXxkPft1WO5hCaPmmzFIgbJ_k',
    appId: '1:1006525163225:web:cec3773ec8a63fc3fc00c8',
    messagingSenderId: '1006525163225',
    projectId: 'park-finder-73fb4',
    authDomain: 'park-finder-73fb4.firebaseapp.com',
    storageBucket: 'park-finder-73fb4.appspot.com',
    measurementId: 'G-1PH438GV6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwq9xqChzrUyZywVgQ1DyemCQzveTVnbM',
    appId: '1:1006525163225:android:d4f48b6ac76f6309fc00c8',
    messagingSenderId: '1006525163225',
    projectId: 'park-finder-73fb4',
    storageBucket: 'park-finder-73fb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJuzildFtidxe0qgXznlaJYUNaDTevG8',
    appId: '1:1006525163225:ios:0ce00b6cf49679c7fc00c8',
    messagingSenderId: '1006525163225',
    projectId: 'park-finder-73fb4',
    storageBucket: 'park-finder-73fb4.appspot.com',
    iosBundleId: 'com.example.parkFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJuzildFtidxe0qgXznlaJYUNaDTevG8',
    appId: '1:1006525163225:ios:0ce00b6cf49679c7fc00c8',
    messagingSenderId: '1006525163225',
    projectId: 'park-finder-73fb4',
    storageBucket: 'park-finder-73fb4.appspot.com',
    iosBundleId: 'com.example.parkFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDgnR-BFNXxkPft1WO5hCaPmmzFIgbJ_k',
    appId: '1:1006525163225:web:3145c080c55ce69dfc00c8',
    messagingSenderId: '1006525163225',
    projectId: 'park-finder-73fb4',
    authDomain: 'park-finder-73fb4.firebaseapp.com',
    storageBucket: 'park-finder-73fb4.appspot.com',
    measurementId: 'G-HQ9WMEN6W5',
  );
}
